version: "3"

services:
  server:
      build: ./server/
      container_name: server
      working_dir: /var/www/server
      ports:
          - 8000:8000
      volumes:
          - ./server/:/var/www/server
          - ./client/:/var/www/client/
      command: python manage.py runserver 0.0.0.0:8000
      environment:
          - DJANGO_SETTINGS_MODULE=server.settings.dev
      env_file:
          - .env
      depends_on:
          - database

  database:
      container_name: database
      image: postgres:latest
      volumes:
        - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql

  client:
      image: node:latest
      container_name: client
      working_dir: /var/www/client/
      command: yarn start
      ports:
          - 3000:3000
      volumes:
          - ./server/:/var/www/server
          - ./client/:/var/www/client/version: "3"

services:
  server:
      build: ./server/
      container_name: server
      working_dir: /var/www/server
      ports:
          - 8000:8000
      volumes:
          - ./server/:/var/www/server
          - ./client/:/var/www/client/
      command: python manage.py runserver 0.0.0.0:8000
      environment:
          - DJANGO_SETTINGS_MODULE=server.settings.dev
      env_file:
          - .env
      depends_on:
          - database

  database:
      container_name: database
      image: postgres:latest
      volumes:
        - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql

  client:
      image: node:latest
      container_name: client
      working_dir: /var/www/client/
      command: yarn start
      ports:
          - 3000:3000
      volumes:
          - ./server/:/var/www/server
          - ./client/:/var/www/client/
