# Generated by Django 2.1.4 on 2019-01-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'ToDo'), (1, 'InProgress'), (2, 'Done')]),
        ),
    ]
