# Generated by Django 2.1.4 on 2019-01-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190102_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'ToDo'), (1, 'InProgress'), (2, 'Done')]),
        ),
    ]
