# Generated by Django 2.1.4 on 2019-01-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190102_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'ToDo'), ('1', 'InProgress'), ('2', 'Done')], max_length=1),
        ),
    ]
