# Generated by Django 2.1.4 on 2019-01-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190102_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
